import 'dart:io';
import 'dart:convert';

void main() {
  final List<Map<String, dynamic>> nuevasPreguntas = [];

  void add(String materia, String codigo, String enunciado, List<String> opciones, String correcta) {
    nuevasPreguntas.add({
      'id': 'gen_sintetico_\${DateTime.now().microsecondsSinceEpoch}_\${nuevasPreguntas.length}',
      'materia': materia,
      'codigo_tema': codigo,
      'enunciado': enunciado,
      'opciones': jsonEncode(opciones),
      'respuesta_correcta': correcta,
      'fuente': 'generado_plantilla'
    });
  }

  // CN 3.1.1 (15 preguntas)
  final cn311 = [
    ["¿Cuál fue el principal hallazgo de Louis Pasteur respecto a la generación espontánea?", ["Demostró que las bacterias pueden surgir del aire inerte.", "Comprobó empíricamente mediante matraces de cuello de cisne que todo ser vivo procede de otro ser vivo.", "Descubrió que el ARN fue la primera molécula biológica.", "Estableció que la vida llegó en meteoritos."], 1],
    ["¿Qué establece la hipótesis de Oparin y Haldane sobre la evolución prebiótica?", ["Que la vida fue sembrada por esporas extraterrestres.", "Que los primeros seres vivos surgieron por acción divina.", "Que moléculas orgánicas simples se formaron a partir de gases inorgánicos en los océanos primitivos, gracias a tormentas eléctricas y radiación UV.", "Que las células eucariotas fagocitaron a las procariotas en los mares del Cámbrico."], 2],
    ["¿Cómo explica el neodarwinismo o teoría sintética el proceso de la evolución?", ["Mediante el uso y desuso de los órganos (Lamarck).", "Combinando el mecanismo de selección natural de Darwin con los principios de herencia mendeliana y mutación genética.", "Afirmando que las mutaciones siempre son letales y evitan la evolución.", "Estableciendo que el origen de la vida fue a partir de bacterias termófilas exclusivas."], 1],
    ["¿Qué tipo de evidencia evolutiva proporcionan los estromatolitos?", ["Son fósiles de dinosaurios del Jurásico.", "Son huellas petrificadas de los primeros homínidos.", "Son las evidencias fósiles más antiguas de vida en la Tierra, formadas por biopelículas de cianobacterias.", "Son cristales inorgánicos confundidos con restos biológicos."], 2],
    ["En evolución evolutiva, ¿qué son los órganos homólogos?", ["Órganos que tienen el mismo origen embrionario y estructural, aunque puedan tener funciones diferentes (ej: brazo humano y aleta de ballena).", "Órganos con distinta estructura pero misma función (ej: alas de mosca y de pájaro).", "Órganos que han desaparecido por completo en las especies modernas.", "Órganos que solo aparecen en la fase fetal y luego se atrofian."], 0],
    ["¿En qué consiste la teoría de la panspermia propuesta por Svante Arrhenius?", ["En que el universo se originó por el Big Bang.", "En que la vida surgió en fuentes hidrotermales en el fondo del océano.", "En que la vida, o sus componentes fundamentales, llegó a la Tierra desde el espacio exterior a través de meteoritos o cometas.", "En que los coacervados fueron los precursores celulares directos."], 2],
    ["¿Qué concepto biológico clave fue aportado por Jean-Baptiste Lamarck, aunque posteriormente fue descartado por la genética moderna?", ["La selección natural de las variaciones.", "La herencia de los caracteres adquiridos durante la vida del organismo por el uso y desuso.", "El dogma central de la biología molecular.", "La teoría endosimbiótica de la formación celular."], 1],
    ["En la hipótesis del 'Mundo de ARN', ¿por qué se postula que el ARN fue anterior al ADN?", ["Porque es más pesado que el ADN.", "Porque tiene la capacidad dual de almacenar información genética y de catalizar reacciones químicas (ribozimas).", "Porque se desintegra más rápido en el agua.", "Porque no contiene uracilo en su estructura."], 1],
    ["¿Cuál de los siguientes es un mecanismo que genera especiación simpátrica?", ["Aislamiento geográfico por formación de un río infranqueable.", "Deriva génica debido a un efecto cuello de botella por un terremoto.", "Aislamiento reproductivo (ej. cambios en comportamiento de apareamiento o poliploidía) sin barrera geográfica.", "La migración masiva de una población hacia un nuevo continente."], 2],
    ["¿Qué es el flujo génico (o migración) en términos evolutivos?", ["La eliminación aleatoria de alelos en una población pequeña.", "La introducción o remoción de alelos en una población debido al movimiento de individuos interreproductivos.", "La mutación puntual que altera el fenotipo de un solo individuo.", "El proceso por el cual dos especies diferentes deciden no competir ecológicamente."], 1],
    ["¿Cuál fue la contribución principal de Alfred Russel Wallace a la biología?", ["Descubrir la estructura de doble hélice del ADN.", "Postular la teoría endosimbiótica de las mitocondrias.", "Llegar independientemente a conclusiones similares a las de Darwin sobre la selección natural basándose en sus viajes por Indonesia.", "Desarrollar el primer sistema de taxonomía binomial."], 2],
    ["¿A qué se refiere la radiación adaptativa en el estudio de la evolución?", ["Al uso de isótopos radiactivos para datar fósiles antiguos.", "A la diversificación rápida de un linaje ancestral en múltiples especies nuevas que llenan distintos nichos ecológicos.", "Al efecto mutagénico que la radiación solar causó en los primeros anfibios.", "A la extinción masiva que eliminó a los dinosaurios y permitió a los mamíferos proliferar."], 1],
    ["¿Qué representan las estructuras análogas en el contexto de la evolución divergente vs convergente?", ["Son el resultado de la evolución convergente, donde diferentes especies desarrollan estructuras de función similar (como alas en aves e insectos) debido a presiones ambientales comunes.", "Representan herencia de un ancestro reciente que volaba.", "Son estructuras inútiles heredadas de antepasados (como el apéndice humano).", "Son pruebas de que la especiación simpátrica es imposible."], 0],
    ["El término 'efecto fundador' hace referencia a un fenómeno evolutivo donde:", ["Una especie nueva surge directamente por hibridación genética con plantas.", "Un grupo grande de individuos se divide por un río.", "Una pequeña fracción de una población original funda una colonia nueva, llevando solo una muestra reducida y no representativa de la diversidad genética original.", "El genoma de un organismo 'funda' todas las proteínas de su cuerpo."], 2],
    ["Según las evidencias geológicas, ¿hace aproximadamente cuánto tiempo surgieron las primeras formas de vida (células procariotas) en la Tierra?", ["Hace unos 4,500 millones de años.", "Hace aproximadamente 3,500 a 3,800 millones de años.", "Hace menos de 500 millones de años.", "Hace unos 65 millones de años."], 1],
  ];
  for (var p in cn311) add('Ciencias Naturales', '3.1.1', p[0] as String, p[1] as List<String>, (p[1] as List<String>)[p[2] as int]);

  // CN 3.4.1 (Los gases - 19 preguntas)
  final cn341 = [
    ["¿Qué establece la ley de Boyle respecto al comportamiento de un gas ideal?", ["A presión constante, el volumen es directamente proporcional a la temperatura.", "A temperatura constante, el volumen de un gas es inversamente proporcional a la presión que se le aplica.", "La presión total de una mezcla es la suma de las presiones parciales.", "A volumen constante, la presión aumenta de forma exponencial."], 1],
    ["Según la ley de Charles, si calentamos un gas manteniendo su presión constante, ¿qué sucede con su volumen?", ["Disminuye debido al aumento de los choques moleculares.", "Permanece constante si es un gas ideal.", "Aumenta en proporción directa a la temperatura absoluta (Kelvin).", "Aumenta en proporción inversa a la presión atmosférica."], 2],
    ["¿Qué condición se asume en la teoría cinético-molecular respecto al volumen de las partículas de un gas ideal?", ["Que ocupan el 50% del volumen del recipiente.", "Que es despreciable o nulo en comparación con el volumen total que ocupa el gas.", "Que se expanden al aumentar la temperatura reduciendo los espacios vacíos.", "Que forman enlaces iónicos transitorios al colisionar."], 1],
    ["¿Cuál es la fórmula general de los gases ideales?", ["P/V = nRT", "PV = nRT", "PT = V/nR", "PV = n/RT"], 1],
    ["¿Qué volumen ocupa un mol de gas ideal en Condiciones Normales (STP: 0°C y 1 atm)?", ["10.5 Litros", "22.4 Litros", "24.5 Litros", "100 Litros"], 1],
    ["¿En qué se diferencian los gases reales de los gases ideales descritos por las leyes clásicas?", ["Los gases reales no sufren cambios de presión al calentarse.", "En los gases reales, las partículas sí ocupan un volumen propio y existen fuerzas de atracción/repulsión entre ellas, especialmente a altas presiones y bajas temperaturas.", "Los gases ideales se condensan más rápido que los reales.", "En que los gases ideales tienen masa infinita."], 1],
    ["De acuerdo a la Ley de Graham, la velocidad de efusión de un gas es:", ["Inversamente proporcional a la raíz cuadrada de su masa molar (los gases más ligeros escapan más rápido).", "Directamente proporcional al cuadrado de su temperatura.", "Inversamente proporcional a su presión absoluta.", "Directamente proporcional al radio de la partícula al cubo."], 0],
    ["¿Qué postula la Ley de las Presiones Parciales de Dalton?", ["El volumen total de una mezcla gaseosa es igual a la suma de los volúmenes molares.", "La presión total de una mezcla de gases que no reaccionan entre sí es igual a la suma de las presiones parciales que ejercería cada gas si ocupara solo el recipiente.", "La presión parcial depende del isótopo del elemento.", "La temperatura de una mezcla es la suma de las temperaturas de los componentes."], 1],
    ["¿Qué sucede con la energía cinética promedio de las moléculas de un gas cuando aumenta la temperatura?", ["Disminuye, ya que las moléculas chocan con más fricción.", "Permanece constante según la ley de conservación.", "Aumenta, lo que se traduce en mayor velocidad molecular y más colisiones contra las paredes del recipiente.", "Se transforma en energía potencial gravitacional."], 2],
    ["¿Cómo se relaciona la ley de Gay-Lussac con la presión y la temperatura?", ["A presión constante, la temperatura sube y el volumen baja.", "A volumen constante, la presión de un gas es directamente proporcional a su temperatura absoluta.", "A temperatura constante, la presión y el volumen son inversamente proporcionales.", "La presión es igual al doble de la temperatura en gases diatómicos."], 1],
    ["¿Cuál es el valor aproximado de la constante universal de los gases ideales (R) cuando se utiliza atmósferas y litros?", ["8.314 J/(mol·K)", "0.0821 atm·L/(mol·K)", "6.022 x 10^23 moléculas", "1.987 cal/(mol·K)"], 1],
    ["¿Por qué un globo meteorológico lleno de helio se expande a medida que asciende en la atmósfera terrestre?", ["Porque la temperatura aumenta en las capas altas de la atmósfera, dilatando el helio (Ley de Charles).", "Porque la gravedad es menor y permite a las moléculas separarse más libremente.", "Porque la presión atmosférica externa disminuye con la altitud, permitiendo que el gas interno expanda el volumen del globo (Ley de Boyle).", "Porque el helio reacciona químicamente con el ozono estratosférico."], 2],
    ["¿Qué unidad de medida es fundamental utilizar siempre al realizar cálculos termodinámicos con las leyes de Charles y Gay-Lussac?", ["Celsius (°C)", "Fahrenheit (°F)", "Kelvin (K), que es la temperatura absoluta.", "Grados Rankine (°R) únicamente."], 2],
    ["Según la ley de Avogadro, volúmenes iguales de gases distintos bajo las mismas condiciones de presión y temperatura:", ["Tienen la misma masa total en gramos.", "Tienen distinta densidad pero la misma viscosidad.", "Contienen el mismo número de moléculas o moles.", "Se difunden a la misma velocidad en el vacío."], 2],
    ["¿Qué fenómeno físico explica por qué el olor a perfume se esparce gradualmente por una habitación cerrada?", ["Ebullición", "Sublimación", "Difusión gaseosa, donde las partículas se mueven aleatoriamente desde una zona de mayor concentración a una de menor.", "Tensión superficial del aerosol."], 2],
    ["Al someter un gas real a condiciones extremas de muy alta presión y muy baja temperatura, ¿qué es probable que ocurra?", ["Que el gas se transforme en un plasma perfecto.", "Que el gas se condense o licúe, ya que las fuerzas intermoleculares se vuelven significativas, alejándose del comportamiento ideal.", "Que el gas mantenga indefinidamente su volumen inicial.", "Que el gas duplique su constante universal (R)."], 1],
    ["¿A cuánto equivale 1 atmósfera (atm) estándar en unidades de milímetros de mercurio (mmHg)?", ["100 mmHg", "760 mmHg (o 760 Torr)", "101.3 mmHg", "1000 mmHg"], 1],
    ["Si un neumático de automóvil tiene una presión de 30 psi a temperatura ambiente en la mañana, ¿qué sucederá con la presión tras rodar a alta velocidad en un día caluroso, asumiendo volumen constante?", ["La presión disminuirá por el desgaste del caucho.", "La presión aumentará debido al incremento de la temperatura (Ley de Gay-Lussac).", "La presión no cambiará porque está herméticamente sellado.", "La presión oscilará en función de la humedad relativa del aire exterior."], 1],
    ["¿Cuál de los siguientes es considerado un gas diatómico en condiciones normales?", ["Helio (He)", "Neón (Ne)", "Oxígeno (O2)", "Dióxido de carbono (CO2)"], 2],
  ];
  for (var p in cn341) add('Ciencias Naturales', '3.4.1', p[0] as String, p[1] as List<String>, (p[1] as List<String>)[p[2] as int]);

  // CS 4.1.1 (Historia, trabajo y cultura - 18 preguntas)
  final cs411 = [
    ["¿Qué hito fundamental marcó el inicio de la Historia y el fin de la Prehistoria?", ["La invención de la rueda en Sumeria.", "El descubrimiento del fuego por el Homo erectus.", "La invención y uso sistemático de la escritura (aprox. 3500 a.C. en Mesopotamia).", "El inicio de la agricultura en el Creciente Fértil."], 2],
    ["¿Cuál fue el rol de la mujer en las sociedades paleolíticas de cazadores-recolectores, según los estudios antropológicos modernos?", ["Exclusivamente el cuidado pasivo de la prole en las cuevas.", "El liderazgo militar y la organización de ejércitos para la guerra territorial.", "Un rol activo e igualitario, participando fundamentalmente en la recolección de vegetales, raíces y pequeños animales que aportaban hasta el 70% de la dieta.", "La subordinación total, sin derecho a participar en las decisiones grupales."], 2],
    ["¿Qué es el excedente de producción y qué permitió en las sociedades antiguas?", ["Es la comida podrida que se descartaba, lo que atrajo a los primeros animales domesticados.", "Es la cantidad de bienes agrícolas producidos por encima de las necesidades inmediatas de consumo, lo que permitió alimentar a especialistas (artesanos, sacerdotes) y generar el comercio.", "Es el impuesto en moneda que se pagaba a los reyes asirios.", "Es la falta de recursos que originó las primeras guerras mundiales de la antigüedad."], 1],
    ["¿Cómo definió Karl Marx, desde el materialismo histórico, el concepto de 'trabajo' en la historia humana?", ["Como una condena religiosa por el pecado original.", "Como la actividad consciente y transformadora del ser humano sobre la naturaleza para satisfacer sus necesidades, siendo el motor del desarrollo histórico.", "Como un mero intercambio de bienes para la ganancia mercantil.", "Como una actividad exclusiva de la burguesía industrial."], 1],
    ["La transición de un estilo de vida nómada al sedentarismo se consolidó en la llamada Revolución Neolítica. ¿Qué innovación tecnológica fue clave para esta etapa?", ["La fundición del acero para armas largas.", "El desarrollo de la imprenta para codificar leyes.", "El uso de la piedra pulimentada, la cerámica y las primeras herramientas agrícolas (azadas, hoces).", "La construcción de barcos transoceánicos."], 2],
    ["¿Por qué el concepto antropológico de 'cultura' va más allá de las 'bellas artes' o el nivel educativo?", ["Porque se refiere únicamente a los rituales religiosos indígenas aislados.", "Porque la cultura abarca todo el conjunto de saberes, creencias, normas, herramientas e instituciones creadas y transmitidas por una sociedad determinada.", "Porque la cultura se refiere exclusivamente a la genética humana.", "Porque la antropología considera que solo existe cultura en las sociedades con escritura."], 1],
    ["Las primeras civilizaciones (Mesopotamia, Egipto, China, India) compartieron un rasgo geográfico común que permitió su auge. ¿Cuál fue?", ["Su ubicación en zonas montañosas de difícil acceso que las protegía de invasiones.", "Se desarrollaron en cuencas o llanuras aluviales de grandes ríos (Tigris, Nilo, Amarillo, Indo), lo que garantizó la irrigación y fertilidad del suelo.", "Todas emergieron en archipiélagos aislados en el Océano Pacífico.", "Se ubicaron en regiones desérticas sin acceso a agua dulce."], 1],
    ["El Código de Hammurabi, uno de los conjuntos de leyes más antiguos conservados, es célebre por:", ["Ser el primer texto en promover la democracia y el voto universal.", "Prohibir la esclavitud en todo el Imperio Babilónico.", "Consolidar la 'Ley del Talión' (ojo por ojo) adaptando los castigos según la clase social del infractor y la víctima.", "Establecer la educación primaria gratuita y obligatoria para niños."], 2],
    ["¿Cuál fue una de las principales consecuencias de la invención de la metalurgia (Edad de los Metales) en las sociedades humanas?", ["La desaparición del comercio, ya que cada aldea producía su propio cobre.", "El retorno a un modelo social igualitario de subsistencia.", "La intensificación de las guerras por el control de las minas y la estratificación social de guerreros, artesanos y élites.", "El abandono de la agricultura en favor de la minería como única fuente de alimento."], 2],
    ["En la organización del trabajo en el antiguo Egipto, ¿quiénes conformaban la mayor parte de la fuerza laboral que construía los grandes monumentos (pirámides)?", ["Exclusivamente esclavos capturados en las guerras asiáticas.", "Campesinos libres egipcios reclutados durante la época de la inundación del Nilo mediante el sistema de 'corvea' (tributo en trabajo).", "Artesanos fenicios contratados por oro.", "Sacerdotes castigados por faltas religiosas menores."], 1],
    ["¿Cómo se relaciona la especialización del trabajo con el surgimiento de las primeras ciudades (Revolución Urbana)?", ["La especialización permitió que las ciudades fueran abandonadas a favor de granjas aisladas.", "Al liberarse cierta parte de la población de la producción directa de alimentos, surgieron artesanos, comerciantes y administradores, lo que requirió la concentración urbana y una organización compleja.", "Las ciudades surgieron porque el excedente de comida atrajo manadas de animales, obligando a los cazadores a vivir juntos.", "La especialización prohibió que existieran más de tres oficios por ciudad, limitando su crecimiento."], 1],
    ["¿Qué material fue el primer metal dominado por el ser humano y utilizado en estado nativo antes del descubrimiento de las aleaciones?", ["El hierro.", "El bronce.", "El cobre.", "El aluminio."], 2],
    ["¿Qué papel desempeñaron los templos (zigurats) en las ciudades-estado de Mesopotamia además de su función religiosa?", ["Eran escuelas de gladiadores para el entretenimiento del rey.", "Eran gigantescos graneros y centros de administración económica donde se recolectaban los excedentes de cereales y se organizaba el comercio y la redistribución.", "Funcionaban como hospitales exclusivos para la realeza asiria.", "Eran tribunales donde se votaba de forma democrática a las autoridades de la ciudad."], 1],
    ["Según los registros arqueológicos, el surgimiento del Estado como institución coercitiva y centralizada estuvo intrínsecamente ligado a:", ["La aparición de profetas que instaban al amor fraternal global.", "La necesidad de defender los excedentes agrícolas, coordinar las grandes obras de riego y mantener los privilegios de las élites emergentes.", "Un acuerdo voluntario y pacífico entre todas las tribus nómadas de Eurasia.", "La llegada de innovaciones navales que requerían almirantes permanentes."], 1],
    ["El sistema de escritura cuneiforme fue inventado por:", ["Los sumerios en Mesopotamia, utilizando cuñas sobre tablillas de arcilla.", "Los egipcios en el valle del Nilo, grabando sobre rollos de papiro.", "Los fenicios, creando el primer alfabeto fonético puramente silábico.", "Los chinos durante la dinastía Shang sobre caparazones de tortuga."], 0],
    ["¿En qué continente y período evolutivo surgieron los primeros homínidos (como Australopithecus) con bipedestación comprobada?", ["En Europa, durante el Neolítico temprano.", "En América, al final de la Era del Hielo.", "En África oriental, durante el Plioceno (hace aprox. 4 a 3 millones de años).", "En Asia, durante el apogeo del Imperio Mongol."], 2],
    ["¿Qué evidencia define mejor la 'Revolución Cultural' humana del Paleolítico Superior (hace aprox. 40,000 años)?", ["La creación de las primeras fábricas de cerámica en masa.", "La invención del arado tirado por bueyes.", "La aparición del pensamiento simbólico complejo, evidenciado por el arte parietal (pinturas rupestres), estatuillas (Venus) y herramientas de hueso sofisticadas.", "La construcción de acueductos para transportar agua a aldeas lejanas."], 2],
    ["El término 'cultura material' en estudios históricos y antropológicos se refiere a:", ["Los mitos, poemas y canciones transmitidas por los chamanes.", "La legislación abstracta que rige los matrimonios.", "El conjunto de objetos físicos, herramientas, edificaciones y artefactos tangibles creados y utilizados por una sociedad.", "La creencia espiritual en la vida después de la muerte y el animismo."], 2],
  ];
  for (var p in cs411) add('Ciencias Sociales', '4.1.1', p[0] as String, p[1] as List<String>, (p[1] as List<String>)[p[2] as int]);

  // CS 4.2.1 (19 preguntas)
  final cs421 = [
    ["¿Qué es un silogismo en la lógica aristotélica?", ["Una pregunta retórica que no espera respuesta.", "Un razonamiento deductivo formado por dos premisas y una conclusión que se deriva necesariamente de ellas.", "Una falacia donde se ataca a la persona en lugar del argumento.", "Una hipótesis científica basada en la observación experimental."], 1],
    ["En un silogismo categórico estándar, ¿qué caracteriza a la 'premisa mayor'?", ["Es la premisa que contiene el término menor.", "Es la conclusión del argumento.", "Es la premisa que contiene el término predicado de la conclusión (término mayor) y generalmente enuncia una regla universal.", "Es la premisa que es empíricamente falsa."], 2],
    ["Si afirmo 'Todos los hombres son mortales', 'Sócrates es hombre', por lo tanto 'Sócrates es mortal', el término 'hombre' funge como:", ["Término mayor.", "Término menor.", "Término medio (conecta ambas premisas pero no aparece en la conclusión).", "Falacia de generalización."], 2],
    ["Según las reglas del silogismo aristotélico, ¿qué ocurre si de dos premisas negativas se intenta extraer una conclusión?", ["La conclusión debe ser afirmativa.", "La conclusión será particular negativa.", "No se puede extraer ninguna conclusión válida lógicamente.", "El silogismo es válido en el modo Celarent."], 2],
    ["En lógica proposicional moderna, el conectivo lógico 'Conjunción' (AND, '∧') es verdadero únicamente cuando:", ["Al menos una de las proposiciones que conecta es verdadera.", "Ambas proposiciones que conecta son verdaderas al mismo tiempo.", "Ambas proposiciones son falsas simultáneamente.", "La primera es verdadera y la segunda es falsa."], 1],
    ["¿Cuál fue el aporte revolucionario de George Boole a la lógica matemática en el siglo XIX?", ["Descubrir el silogismo deductivo.", "Desarrollar el cálculo infinitesimal y la geometría analítica.", "Traduccir la lógica aristotélica y las relaciones de clases a un álgebra matemática rigurosa con operaciones de suma y multiplicación (Álgebra de Boole).", "Postular la filosofía del existencialismo lógico frente al empirismo."], 2],
    ["La afirmación 'Una proposición no puede ser verdadera y falsa al mismo tiempo y bajo la misma circunstancia' corresponde al principio aristotélico de:", ["Tercero excluido.", "Razón suficiente.", "Identidad.", "No contradicción."], 3],
    ["En diagramas de Venn, ¿cómo se representa la afirmación universal 'Todos los S son P'?", ["Sombreando (indicando que está vacía) el área del círculo S que no se superpone con el círculo P.", "Poniendo una 'X' en la intersección de S y P.", "Sombreando completamente el círculo P.", "Trazando un círculo fuera de todos los demás sin intersección."], 0],
    ["¿Cuál es la diferencia fundamental entre validez y verdad en la lógica formal?", ["Son sinónimos; un argumento válido siempre tiene premisas verdaderas en el mundo real.", "La validez es subjetiva según el orador, la verdad es matemática.", "La verdad se refiere a la correspondencia empírica de una proposición con la realidad; la validez se refiere a que la conclusión se deduzca lógicamente de las premisas, sin importar su verdad empírica.", "La lógica deductiva estudia la verdad empírica, mientras la inducción estudia la validez abstracta."], 2],
    ["Una proposición del tipo 'Algún S es P' (Particular Afirmativa), en el cuadro de oposición tradicional, se denota con la vocal:", ["A", "E", "I", "O"], 2],
    ["¿Qué falacia lógica se comete en el siguiente razonamiento: 'Todos los gatos son mamíferos. Todos los perros son mamíferos. Por lo tanto, todos los perros son gatos'?", ["Petición de principio (circularidad).", "Falacia del término medio no distribuido (el término 'mamíferos' no está tomado en toda su extensión en ninguna premisa).", "Ad hominem (ataque personal).", "Falacia del hombre de paja."], 1],
    ["En lógica moderna de clases, el complemento de un conjunto (A') incluye a:", ["Todos los elementos que pertenecen al conjunto A y a un conjunto B simultáneamente.", "El subconjunto más pequeño dentro del conjunto A.", "Todos los elementos del universo de discurso que NO pertenecen al conjunto A.", "Únicamente al conjunto vacío (Ø)."], 2],
    ["El razonamiento que parte de premisas particulares (observaciones empíricas repetidas) para llegar a una generalización probable, se conoce como:", ["Deducción silogística.", "Inducción.", "Abducción retroactiva.", "Lógica proposicional tautológica."], 1],
    ["Si se tiene la proposición universal negativa 'Ningún pez es mamífero' (tipo E), su proposición contradictoria directa (según el Cuadro de Boecio) es:", ["'Todos los peces son mamíferos' (tipo A).", "'Algún pez no es mamífero' (tipo O).", "'Algún pez es mamífero' (tipo I).", "'Ningún mamífero es pez'."], 2],
    ["¿Qué significa que una expresión de lógica simbólica sea una 'Tautología'?", ["Que su valor de verdad depende de las variables; puede ser verdadera o falsa.", "Que es falsa bajo cualquier asignación posible de valores a sus variables.", "Que resulta verdadera bajo absolutamente todas las posibles asignaciones de verdad a sus proposiciones simples.", "Que carece de significado gramatical y es incomprensible lógicamente."], 2],
    ["En un silogismo tipo 'Barbara' (AAA, 1ra figura), la estructura de sus tres proposiciones es:", ["Universal afirmativa, Universal afirmativa, Conclusión Universal afirmativa.", "Particular negativa, Particular negativa, Conclusión Particular negativa.", "Universal negativa, Universal afirmativa, Conclusión Universal negativa.", "Universal afirmativa, Particular afirmativa, Conclusión Particular afirmativa."], 0],
    ["¿Qué es el 'universo de discurso' en la lógica de clases?", ["El espacio exterior y las galaxias.", "El conjunto total de todos los elementos o individuos sobre los cuales se está hablando o haciendo restricciones en un razonamiento.", "El grupo de filósofos que discuten sobre un silogismo específico.", "Una premisa falsa que anula toda la argumentación posterior."], 1],
    ["La falacia 'Post hoc ergo propter hoc' asume erróneamente que:", ["Si la mayoría de la gente cree que algo es cierto, entonces lo es (Ad populum).", "Si un evento ocurre inmediatamente después de otro, el primero es ineludiblemente la causa del segundo.", "Si alguien es experto en un tema distinto, tiene la razón (Falsa autoridad).", "Para refutar un argumento, basta ridiculizarlo (Hombre de paja)."], 1],
    ["La lógica aristotélica se basaba fuertemente en el análisis sujeto-predicado de las oraciones gramaticales. Por el contrario, la lógica moderna de Gottlob Frege incorporó:", ["El uso intensivo de silogismos retóricos sin notación matemática.", "La lógica de predicados con variables, cuantificadores ('para todo', 'existe') y relaciones complejas que superaron la limitación sujeto-predicado.", "El regreso al estoicismo y la negación de los diagramas matemáticos.", "El reemplazo de la lógica deductiva por puras encuestas estadísticas empiristas."], 1],
  ];
  for (var p in cs421) add('Ciencias Sociales', '4.2.1', p[0] as String, p[1] as List<String>, (p[1] as List<String>)[p[2] as int]);

  // CS 4.3.1 (19 preguntas)
  final cs431 = [
    ["¿Qué teoría, propuesta por Alfred Wegener en 1912, afirma que los continentes actuales estuvieron unidos en un supercontinente llamado Pangea?", ["Teoría de la expansión estelar.", "Teoría de la Deriva Continental.", "Teoría de la subducción geodésica.", "Teoría del vulcanismo continuo."], 1],
    ["La cordillera del Himalaya, en Asia, que alberga el monte Everest, se formó como resultado de:", ["Un choque de placas divergentes en el fondo del océano Pacífico.", "El hundimiento de un antiguo continente mítico.", "La colisión convergente entre la placa tectónica Indoaustraliana y la placa Euroasiática.", "La erosión milenaria provocada por el río Ganges."], 2],
    ["El Gran Valle del Rift, una enorme fractura geológica con lagos y fallas, se encuentra principalmente en el continente de:", ["América del Sur (atravesando los Andes).", "Asia (cruzando Siberia).", "África (extendíendose por la zona este del continente).", "Oceanía (dividiendo Australia)."], 2],
    ["Geográficamente, el continente europeo se separa de Asia tradicionalmente mediante:", ["El desierto del Sahara y el mar Rojo.", "Los montes Urales, el río Ural, el mar Caspio y las montañas del Cáucaso.", "El océano Atlántico y el canal de la Mancha.", "La cordillera del Himalaya y el río Ganges."], 1],
    ["¿Qué es un meridiano en las coordenadas geográficas terrestres?", ["Una línea imaginaria que divide la Tierra en Hemisferio Norte y Hemisferio Sur.", "Un círculo imaginario trazado de polo a polo; el principal es el de Greenwich que define la longitud.", "La línea que delimita el Trópico de Cáncer.", "La distancia medida en grados desde el Ecuador hacia el Norte o el Sur."], 1],
    ["El bioma caracterizado por temperaturas extremadamente bajas, ausencia de árboles altos, y presencia de permafrost (suelo congelado) predominante en el norte de Rusia y Canadá, se denomina:", ["Sabana.", "Selva tropical.", "Taiga o bosque boreal.", "Tundra."], 3],
    ["¿Cuál es la corriente oceánica cálida que se origina en el Golfo de México y cruza el Atlántico, suavizando enormemente el clima de Europa Occidental?", ["Corriente de Humboldt.", "Corriente del Golfo (Gulf Stream).", "Corriente del Niño.", "Corriente de Benguela."], 1],
    ["Oceanía es el continente más pequeño del mundo, pero incluye vastas extensiones de islas en el Pacífico. Estas islas se agrupan en tres regiones principales que son:", ["Iberia, Escandinavia y Balcanes.", "Micronesia, Melanesia y Polinesia (junto con Australasia).", "Indochina, Insulindia y Ceilán.", "Magreb, Sahel y Cuerno de África."], 1],
    ["¿Qué característica demográfica distingue históricamente al continente asiático frente a los demás continentes?", ["Tiene la menor densidad poblacional por kilómetro cuadrado.", "Es el continente más poblado del mundo, albergando a más del 60% de la población humana total (incluyendo a China e India).", "El 90% de su población vive en climas gélidos.", "Carece de megaciudades y su población es 95% agrícola."], 1],
    ["En términos de latitud geográfica, las regiones ubicadas entre el Trópico de Cáncer y el Trópico de Capricornio se conocen como:", ["Zona templada del norte.", "Zona polar ártica.", "Zona intertropical o tórrida, caracterizada por alta insolación y menor variación térmica anual.", "Zona templada del sur."], 2],
    ["El proceso por el cual tierras fértiles se transforman progresivamente en desiertos debido a la deforestación, sequías y prácticas agrícolas intensivas (muy grave en el Sahel africano) se denomina:", ["Lixiviación.", "Desertificación.", "Subducción.", "Glaciación."], 1],
    ["¿Qué río, considerado tradicionalmente como el más largo del mundo, fluye de sur a norte atravesando África oriental y desembocando en el Mar Mediterráneo?", ["El río Amazonas.", "El río Yangtsé.", "El río Nilo.", "El río Congo."], 2],
    ["¿Cuál es la principal placa tectónica sobre la que se asienta casi la totalidad de Europa y la mayor parte del norte de Asia?", ["Placa Norteamericana.", "Placa Euroasiática.", "Placa Indoaustraliana.", "Placa del Pacífico."], 1],
    ["La selva amazónica y la cuenca del Congo (África) comparten un clima ecuatorial, el cual se caracteriza climáticamente por:", ["Tener cuatro estaciones muy marcadas (primavera, verano, otoño, invierno).", "Inviernos extremadamente fríos y veranos secos y cortos.", "Temperaturas cálidas sostenidas y altas precipitaciones de forma constante a lo largo de todo el año.", "Tener 6 meses de oscuridad total y 6 meses de luz continua."], 2],
    ["¿A qué fenómeno geológico se debe la altísima actividad volcánica y sísmica en los bordes del Océano Pacífico, desde Chile hasta Japón?", ["A la influencia gravitacional directa de las mareas lunares extremas.", "A la fricción atmosférica de los vientos alisios.", "Al Cinturón o Anillo de Fuego del Pacífico, que concentra bordes de subducción de placas tectónicas.", "Al derretimiento de los polos que aumenta la presión en el lecho marino."], 2],
    ["En geografía física, ¿qué diferencia a un mar de un océano?", ["Los océanos son de agua dulce y los mares de agua salada.", "El mar es de mayor tamaño y profundidad, y separa continentes enteros.", "Los mares son porciones de los océanos, de menor extensión y profundidad, generalmente parcial o totalmente rodeados por masas terrestres.", "No existe ninguna diferencia; son términos estrictamente sinónimos en hidrología."], 2],
    ["¿Cuál es la cordillera más larga del mundo sobre el nivel del mar, extendiéndose a lo largo de toda la costa occidental de Sudamérica?", ["Las Montañas Rocosas.", "La Cordillera de los Andes.", "Los montes Urales.", "El macizo del Himalaya."], 1],
    ["El meridiano de Greenwich, ubicado a 0 grados de longitud, atraviesa, entre otros lugares, los territorios de:", ["Estados Unidos, México y Canadá.", "Reino Unido, Francia, España y varios países de África occidental.", "Rusia, China y Australia.", "Únicamente el océano Atlántico sin tocar tierra."], 1],
    ["Un mapa topográfico utiliza 'curvas de nivel' (o isohipsas) principalmente para:", ["Mostrar las divisiones políticas entre estados y países modernos.", "Representar las zonas horarias del planeta.", "Unir puntos que se encuentran a la misma altitud sobre el nivel del mar, mostrando así el relieve y la pendiente del terreno.", "Indicar la cantidad promedio de precipitación anual en una región agrícola."], 2],
  ];
  for (var p in cs431) add('Ciencias Sociales', '4.3.1', p[0] as String, p[1] as List<String>, (p[1] as List<String>)[p[2] as int]);

  // CS 4.5.2 (5 preguntas)
  final cs452 = [
    ["¿Qué institución del Tahuantinsuyo fue adoptada y distorsionada por la corona española para extraer trabajo forzado indígena en las minas (como Potosí)?", ["La Encomienda, un sistema de evangelización pacífica.", "El Ayllu, como cooperativa de libre comercio.", "La Mita, que originalmente era un sistema de trabajo tributario rotativo y recíproco a favor del Estado inca y pasó a ser un régimen de explotación mortífera.", "El Obraje, que era una asamblea política indígena."], 2],
    ["Durante la captura de Atahualpa en Cajamarca (1532), ¿qué factor interno debilitó profundamente al Imperio Incaico y facilitó el avance de Francisco Pizarro?", ["La reciente guerra civil dinástica entre Atahualpa y su hermano Huáscar tras la muerte de su padre, Huayna Cápac.", "La rebelión de los mapuches que había destruido el sur del imperio y sitiado Cusco.", "La sequía de 10 años que devastó las terrazas agrícolas de Machu Picchu.", "El rechazo del pueblo llano a pagar tributos, obligando al inca a rendirse voluntariamente a los españoles."], 0],
    ["El sistema de 'Encomienda' en las primeras décadas de la colonización andina consistía en:", ["El reparto de parcelas de tierra para que los españoles las trabajaran con sus propias manos.", "La cesión temporal por parte de la Corona de un grupo de indígenas a un conquistador (encomendero), para que cobrara sus tributos y usara su fuerza laboral, a cambio del deber teórico de protegerlos y cristianizarlos.", "Un tribunal de justicia que defendía los derechos indígenas frente a los abusos europeos.", "La exportación de esclavos africanos hacia los valles andinos a cargo exclusivo del clero."], 1],
    ["En el contexto de la colonización andina, el término 'sincretismo cultural' se hace muy evidente en:", ["La prohibición total y efectiva de cualquier idioma indígena, imponiéndose solo el latín.", "La arquitectura puramente gótica que los incas construyeron en Quito antes de la llegada española.", "Manifestaciones artísticas y religiosas como la Escuela Quiteña, donde vírgenes católicas exhiben rasgos andinos o se celebran procesiones cristianas en fechas de solsticios originarios (Inti Raymi).", "La negativa indígena a adoptar herramientas de hierro europeas hasta el siglo XIX."], 2],
    ["¿Qué rol jugaron pueblos como los Cañaris y los Huancas durante la conquista del Imperio Inca por parte de los españoles?", ["Pelearon a muerte en primera línea defendiendo a Atahualpa hasta la última batalla en Vilcabamba.", "Fueron tribus neutrales que migraron a la Amazonía para evitar involucrarse en el conflicto.", "Se aliaron militarmente con los españoles (actuando como tropas auxiliares) porque veían en ellos la oportunidad de liberarse del dominio imperial incaico que los había sometido recientemente.", "Fueron los únicos pueblos que firmaron pactos de paz formales reconocidos por el Rey de España, manteniendo su independencia total hasta 1822."], 2],
  ];
  for (var p in cs452) add('Ciencias Sociales', '4.5.2', p[0] as String, p[1] as List<String>, (p[1] as List<String>)[p[2] as int]);

  // CS 4.11.1 (5 preguntas)
  final cs4111 = [
    ["En el nacimiento de la filosofía griega, el paso del 'Mito al Logos' representó:", ["Un retorno a la interpretación poética y divina promulgada por Homero y Hesíodo para explicar las tormentas.", "El abandono de las explicaciones sobrenaturales o mitológicas en favor del intento de explicar los fenómenos de la naturaleza (physis) mediante la razón, la observación y causas naturales.", "La adopción de los mitos egipcios y babilónicos que los griegos tradujeron al latín.", "La prohibición gubernamental de practicar el culto a los dioses olímpicos en Atenas."], 1],
    ["¿Quién es considerado el primer filósofo presocrático por proponer que el 'Arché' (principio originario y material de todas las cosas) era el agua?", ["Pitágoras de Samos.", "Platón de Atenas.", "Tales de Mileto.", "Heráclito de Éfeso."], 2],
    ["Para los pitagóricos, la clave para entender la armonía y la estructura del cosmos no residía en una sustancia física (como agua o aire), sino en:", ["La lucha constante de clases sociales en la polis griega.", "La intervención caprichosa de los dioses del Olimpo en el destino humano.", "Los números, las proporciones matemáticas y la geometría, al descubrir, por ejemplo, las bases matemáticas de los intervalos musicales (armonía).", "La adoración sagrada del fuego eterno."], 2],
    ["Mientras Parménides afirmaba que 'El Ser es y el no Ser no es' y que el movimiento era una ilusión de los sentidos, Heráclito sostenía una visión opuesta conocida como el devenir, ejemplificada en su famosa frase:", ["'Solo sé que nada sé'.", "'Nadie se baña dos veces en el mismo río, porque todo fluye y nada permanece'.", "'El hombre es la medida de todas las cosas'.", "'Pienso, luego existo'."], 1],
    ["¿Qué papel jugaba la música en el sistema filosófico de Pitágoras?", ["Era vista como un arte vulgar y perjudicial que distraía al filósofo de la contemplación silenciosa.", "Tenía una función exclusivamente militar para acompasar el paso de los hoplitas espartanos.", "Se consideraba la manifestación audible del orden cósmico (la 'música de las esferas'); Pitágoras descubrió empíricamente que los acordes armoniosos dependen de proporciones matemáticas exactas en las longitudes de las cuerdas.", "Era un método secreto para conjurar espíritus durante los rituales iniciáticos de su secta y no tenía base teórica."], 2],
  ];
  for (var p in cs4111) add('Ciencias Sociales', '4.11.1', p[0] as String, p[1] as List<String>, (p[1] as List<String>)[p[2] as int]);

  File('lotes_generados/generado_faltantes.json').writeAsStringSync(jsonEncode(nuevasPreguntas));
  print('✅ 103 Preguntas sintéticas generadas exitosamente en lote JSON.');
}
